package analyzer;

import java.util.Arrays;
import java.util.List;

import util.Global;
import util.Logger;
import util.Logger.MsgType;

/*
 * Default expander adds the top most relevant word in the revisedQuery
 */

public class DefaultExpander extends Expander {

	@Override
	public void expand(String[] query, List<String> revisedQuery) {
		
		Logger myLogger = Logger.getInstance();
		
		revisedQuery.addAll(Arrays.asList(query));
		
		if(Global.getRelevantTerms().size() > 0) {
			revisedQuery.add(Global.getRelevantTerms().get(0));
			myLogger.write("Revised Query Generated by Default Expander: " + 
							revisedQuery.toString(), MsgType.DEBUG);
		}
		else {
			myLogger.write("Error: Default Expander failed to generate revised query " +
					"due to lack of relevant terms" , MsgType.DEBUG);
		}
	}
}
