How to compile?

Go to the 'relevance' directory, type command:
	javac -cp ".:lib/*" RelevanceFeedback.java

How to run?

Go to the 'relevance' directory, type command:
	java -cp ".:lib/*" RelevanceFeedback <ApiKey> <topK> <precision> <'query'>

	example: java -cp ".:lib/*" RelevanceFeedback your-api-key 10 0.8 'bill gates'


More detailed instructions about compiling and running our codes can be found in the README file.